import * as S from "./Fit4All.atoms";
import Image from "next/image";
import { useTranslation } from "next-i18next";

export const Fit4all = () => {
  const { t } = useTranslation("f4a");
  return (
    <S.Container>
      <S.Header>
        <S.Row>
          <h1>Fit4All</h1>
        </S.Row>
      </S.Header>
      <S.Section>
        <S.Row>
          <S.TextBox>
            <h2>Fit4All</h2>
            <p>{t("desc")}</p>
          </S.TextBox>
        </S.Row>
      </S.Section>
      <S.Section>
        <S.Row>
          <S.TextBox>
            <h2>{t("beginning_title")}</h2>
            <p>{t("beginning")}</p>
          </S.TextBox>
          <S.TechLogos>
            <Image
              src="/static/nestjs.svg"
              width={150}
              height={150}
              id="nest"
            />
            <Image
              src="/static/nextjs.svg"
              width={150}
              height={150}
              id="next"
            />
          </S.TechLogos>
        </S.Row>
      </S.Section>
      <S.Section>
        <S.Row>
          <S.TextBox>
            <h2>{t("auth_title")}</h2>
            <p>{t("auth")}</p>
          </S.TextBox>
        </S.Row>
      </S.Section>
      <S.Section>
        <S.Row>
          <S.TextBox>
            <h2>{t("test_title")}</h2>
            <p>{t("test")}</p>
          </S.TextBox>
        </S.Row>
      </S.Section>
      <S.Section>
        <S.Row>
          <S.TextBox>
            <h2>{t("db_title")}</h2>
            <p>{t("db")}</p>
          </S.TextBox>
          <S.ImageShadow>
            <S.DbImageContainer>
              <Image
                src="/static/encrypted_column.svg"
                width={940}
                height={748}
              />
            </S.DbImageContainer>
          </S.ImageShadow>
        </S.Row>
      </S.Section>
    </S.Container>
  );
};
