export const fsName = "Programozási nyelv";
export const fsDesc="llvm alapú, fordított, általános célú programozási nyelv"
export const phdName ="Phd";
export const phdDesc="Több nyelven kézírásfelismerés módszerek mesterséges inteligenciával";
export const cvName="Weboldal"
export const cvDesc="React alapú modern személyes weboldal";
export const appName ="Android Alkalmazás";
export const appDesc ="Native android alkalmazás, helymeghatározással és adatbázissal";
export const tdkName ="Tdk";
export const tdkDesc="Adat augmentálási technikák kézirásfelsimeréshez";